"""Rebuild manuscript sources. Requires Pandoc; PDFs use latexmk -lualatex."""
from pathlib import Path
import csv, json, os, re, shutil, subprocess
P = Path(__file__).resolve().parent
pandoc = os.environ.get('PANDOC') or shutil.which('pandoc')
pandoc_data_dir = os.environ.get('PANDOC_DATA_DIR')
pandoc_prefix = [pandoc] + (['--data-dir='+pandoc_data_dir] if pandoc_data_dir else [])
if not pandoc:
    raise SystemExit('Set PANDOC to the pandoc executable.')
def latex(text):
    return subprocess.run(pandoc_prefix + [ '-f', 'markdown', '-t', 'latex', '--natbib', '--wrap=none', '--no-highlight'], input=text, text=True, stdout=subprocess.PIPE, check=True).stdout.replace(r'\def\LTcaptype{none}', '')
def main_latex(text):
    rendered = latex(text)
    # Keep short main-text tables together; long source-data tables stay in SI.
    def compact(m):
        table = m.group(0).replace(r'\begin{longtable}[]', r'\begin{tabular}')
        table = table.replace(r'\endhead', '').replace(r'\endlastfoot', '')
        table = table.replace(r'\bottomrule\noalign{}', '', 1)
        table = table.replace(r'\end{longtable}', r'\bottomrule\end{tabular}')
        return r'\begin{center}\begin{minipage}{\linewidth}\small'+'\n'+table+'\n'+r'\end{minipage}\end{center}'
    return re.sub(r'\\begin\{longtable\}\[\].*?\\end\{longtable\}', compact, rendered, flags=re.S)

parts = (P/'abstract.md').read_text().strip().split('\n\n')
title, abstract, keywords = parts[0].lstrip('# '), parts[1], parts[2]
sources = sorted((P/'sections').glob('0[1-6]_*.md'))
assert len(sources) == 6
body = '\n\n'.join(s.read_text().strip() for s in sources)
declarations = (P/'declarations.md').read_text()
md = '# '+title+'\n\nAuthor-review draft. Author metadata pending.\n\n## Abstract\n\n'+abstract+'\n\n'+keywords+'\n\n'+body+'\n\n'+declarations+'\n\n# References\n\n'
# The Markdown includes a readable reference list; TeX uses the canonical BibTeX.
with (P/'references/reference_ledger.csv').open() as f:
    for r in csv.DictReader(f):
        md += f"- **{r['citekey']}**. {r['author']} ({r['year']}). {r['title']}. {r['venue']}. "+(f"https://doi.org/{r['doi']}" if r['doi'] else r['source'])+'\n\n'
(P/'manuscript.md').write_text(md.rstrip()+'\n')
preamble = r'''\documentclass[11pt,a4paper]{article}
\usepackage[margin=22mm]{geometry}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman}
\setsansfont{Latin Modern Sans}
\setmonofont{Latin Modern Mono}
\usepackage{amsmath,amssymb,graphicx,booktabs,longtable,array,calc,etoolbox}
\usepackage[numbers,sort&compress]{natbib}
\usepackage{hyperref,caption,float,fancyvrb}
\hypersetup{hidelinks}
\setcounter{secnumdepth}{-1}
\Urlmuskip=0mu plus 1mu
\RecustomVerbatimEnvironment{verbatim}{Verbatim}{fontsize=\footnotesize}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{fontsize=\footnotesize}
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\providecommand{\pandocbounded}[1]{#1}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>.68\textheight .68\textheight\else\Gin@nat@height\fi}
\makeatother
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\AtBeginEnvironment{longtable}{\small}
\renewcommand{\arraystretch}{1.18}
\setlength{\emergencystretch}{3em}
\setlength{\parskip}{4pt}
\setlength{\parindent}{0pt}
\makeatletter
\setlength{\@fptop}{0pt}
\setlength{\@fpsep}{14pt}
\setlength{\@fpbot}{0pt plus 1fil}
\makeatother
\renewcommand{\topfraction}{0.95}
\renewcommand{\bottomfraction}{0.95}
\renewcommand{\textfraction}{0.06}
\renewcommand{\floatpagefraction}{0.80}

'''
for s in sources:
    s.with_suffix('.tex').write_text('% Generated by build_manuscript.py from '+s.name+'\n'+main_latex(s.read_text()))
main = preamble+'\n\\title{'+latex(title).strip()+'}\n\\author{Author information pending}\n\\date{Author-review draft}\n\\begin{document}\n\\maketitle\n\\begin{abstract}\n'+latex(abstract)+'\\end{abstract}\n'+latex(keywords)
main += ''.join('\\input{sections/'+s.with_suffix('.tex').name+'}\n' for s in sources)
main += latex(declarations)+'\n\\bibliographystyle{unsrtnat}\n\\bibliography{references}\n\\end{document}\n'
(P/'main.tex').write_text(main)
si = re.sub(r'\n# References\s*$', '', (P/'supplementary.md').read_text())
(P/'supplementary.tex').write_text(preamble+'\n\\renewcommand{\\thefigure}{S\\arabic{figure}}\n\\begin{document}\n'+latex(si).replace(r'\begin{figure}', r'\begin{figure}[H]')+'\n\\bibliographystyle{unsrtnat}\n\\bibliography{references}\n\\end{document}\n')
htmlmd = re.sub(r'\]\((figures/[^)]+)\.pdf\)', r'](\1.png)', md.split('\n# References\n')[0])+'\n\n# References\n'
subprocess.run(pandoc_prefix + ['-f','markdown','-t','html5','-s','--mathjax','--citeproc','--bibliography',str(P/'references.bib'),'-M','title='+title,'-o',str(P/'manuscript.html')], input=htmlmd, text=True, check=True)
def words(t):
    t = re.sub(r'!\[.*?\]\([^)]*\)(?:\{[^}]*\})?', '', t, flags=re.S)
    t = re.sub(r'\$\$.*?\$\$|\$[^$]*\$|\[@[^\]]*\]', '', t, flags=re.S)
    t = '\n'.join(l for l in t.splitlines() if not l.startswith('|'))
    return len(re.findall(r"\b[\w]+(?:[-’'][\w]+)*\b", t))
report = {'abstract_words':words(abstract),'body_approx_words_excluding_tables_math_captions':words(body),'section_approx_words':{s.name:words(s.read_text()) for s in sources}, 'source_sections':len(sources),'generated':['manuscript.md','manuscript.html','main.tex','supplementary.tex','sections/*.tex']}
(P/'build/source_sync.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
